### ISSUE TITLE
OSError: [E053] Could not read meta.json from en\meta.json

### ISSUE THREAD

**Issue by ITJaylon** [chrisjbryant/errant#30]
Traceback (most recent call last):
  File "C:/Users/ITJaylon/Desktop/errant/errant/test.py", line 3, in <module>
    annotator = errant.load('en')
  File "C:\Users\ITJaylon\Desktop\errant\errant\__init__.py", line 16, in load
    nlp = nlp or spacy.load(lang, disable=["ner"])
  File "E:\Anaconda\envs\errant_env\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "E:\Anaconda\envs\errant_env\lib\site-packages\spacy\util.py", line 172, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "E:\Anaconda\envs\errant_env\lib\site-packages\spacy\util.py", line 198, in load_model_from_path
    meta = get_model_meta(model_path)
  File "E:\Anaconda\envs\errant_env\lib\site-packages\spacy\util.py", line 253, in get_model_meta
    raise IOError(Errors.E053.format(path=meta_path))
OSError: [E053] Could not read meta.json from en\meta.json

Process finished with exit code 1

**Comment by ITJaylon** [comment]
I just follow the instruction of quick start with the Errant API, however, encountered this problem.

**Comment by chrisjbryant** [comment]
It's hard to tell from that readout, but I'm not sure you installed spacy properly. Try reinstalling everything in a clean venv.

**Comment by ITJaylon** [comment]
Thank you, I'll have a try.
